fruits = []
f1 = input("enter your fruits names")
fruits.append(f1) #append is used to add the value to the list
f2 = input("enter your fruits names")
fruits.append(f2)
f3 = input("enter your fruits names")
fruits.append(f3)
f4 = input("enter your fruits names")
fruits.append(f4)
f5 = input("enter your fruits names")
fruits.append(f5)
f6 = input("enter your fruits names")
fruits.append(f6)
f7 = input("enter your fruits names")
fruits.append(f7)
print(fruits)
